<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQUD1JxT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQUD1JxT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQUD1JxT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQUD1JxT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQUD1JxT\App_KernelDevDebugContainer([
    'container.build_hash' => 'QUD1JxT',
    'container.build_id' => '344d5abd',
    'container.build_time' => 1616146447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQUD1JxT');
